Support the static part of Control4d (experimental)
threestudio-project/threestudio pull request #119
Opened 2023-06-10 15:16 UTC by DSaurus

- Add experimental configs (controlnet-normal/canny, instructpix2pix, control4d-multiviews, magic3d-coarse/fine-multiviews).
- Add multiview dataset which supports loading multi-view images and OpenCV camera model of NeRFStudio.
- Add ControlNet and Instructpix2pix as new guidances.
- Add GanVolumeRenderer, which combines nerf volume renderer with a GAN.
- Add rgb-latent-material which simultaneously outputs rgb and latent features.
- Add solid-rgb-feature-background as the background of Control4D.
- Add magic3d_multiviews system and control4d_multiviews systems. magic3d_multiviews system will be changed to instruct-nerf2nerf system in the future. Control4d_multiviews system can achieve static scene editing given multi-view images.
- Add GAN network utils and LPIPS loss utils.
- Update ReadMe.md.
- Add controlnet_aux to the requirements.txt.

2023-06-13 18:21 UTC, claforte commented
Wow, I just looked at your Control4D project page, the results are amazing! Congratulations and thanks for sharing your code!

2023-06-15 09:14 UTC, DSaurus commented
> Wow, I just looked at your Control4D project page, the results are amazing! Congratulations and thanks for sharing your code!

Hi! Thank you for your kind words. I believe ThreeStudio is an incredibly powerful and scalable framework. It effectively combines numerous impressive 3D generation methods in a concise manner. Currently, I am working on extending ThreeStudio's capabilities to include 3D reconstruction from multi-view images and 3D editing. I will soon share some results obtained using ThreeStudio. Feel free to provide me with any advice or suggestions.

2023-06-21 15:28 UTC, bennyguo requested changes
see comments above

2023-06-21 15:28 UTC, bennyguo commented on configs/control4d-static.yaml
> +tag: "${rmspace:${system.prompt_processor.prompt},_}"
consider adding `basename(data.dataroot)` to the tag so that it reflects which scene is working on

2023-06-21 15:28 UTC, bennyguo commented on configs/control4d-static.yaml
> +  dataroot: dataset/twindom
how about making this `???`

2023-06-21 15:28 UTC, bennyguo commented on configs/experimental/controlnet-canny.yaml
how about moving these test configs to `configs/debugging`? as they are not actually configs for specific methods

2023-06-21 15:28 UTC, bennyguo commented on configs/instructnerf2nerf.yaml
> +tag: "${rmspace:${system.prompt_processor.prompt},_}"
also add `basename(data.dataroot)`?

2023-06-21 15:28 UTC, bennyguo commented on configs/instructnerf2nerf.yaml
> +data:
maybe missing `dataroot: ???`

2023-06-21 15:28 UTC, bennyguo commented on configs/prolificdreamer-patch.yaml
how much VRAM does this take? maybe add instructions about this config in ProlificDreamer example running commands in README

2023-06-21 15:28 UTC, bennyguo commented on threestudio/data/multiview.py
> +    dataroot: str = "dataset/face"
more proper to make it default to ""

2023-06-21 15:28 UTC, bennyguo commented on threestudio/data/multiview.py
> +    train_downsample_resolution: int = 3 # 2^3
will it be more intuitive to just use the real downsample factor (e.g., 8) instead of the power of 2?

2023-06-21 15:28 UTC, bennyguo commented on threestudio/data/multiview.py
> +        print("Loaded frames.")
replace all `print` with `threestudio.info` or `threestudio.debug` to ensure the message only appears once in multi-node DDP. `threestudio.debug` will only show the message with `--verbose`

2023-06-21 15:28 UTC, bennyguo commented on threestudio/models/background/solid_rgb_feature_background.py
how is this different from `solid-color-background` with `n_output_dims > 3`? can we just use that?

2023-06-21 15:28 UTC, bennyguo commented on threestudio/models/guidance/controlnet_guidance.py
how about changing to `stable-diffusion-controlnet-guidance` to be more specific?

2023-06-21 15:28 UTC, bennyguo commented on threestudio/models/guidance/instructpix2pix_guidance.py
how about changing to `stable-diffusion-instructpix2pix-guidance` to be more specific?

2023-06-21 15:28 UTC, bennyguo commented on threestudio/utils/lpips/lpips.py
consider changing the folder and this file to `perceptual`?

2023-06-21 18:14 UTC, DSaurus commented on threestudio/models/background/solid_rgb_feature_background.py
They are very similar, I think we can directly use ```solid-color-background```.

2023-06-23 18:31 UTC, bennyguo commented
Looks good enough! I'll merge this PR.

2023-06-23 18:31 UTC, bennyguo approved these changes

2023-06-23 18:32 UTC, merged