Stabilize the GPU memory usage
threestudio-project/threestudio pull request #174
Opened 2023-06-23 17:57 UTC by DSaurus

The GPU memory usage during training with high-resolution settings is currently unstable, leading to OOM errors. The primary factor contributing to this issue is the grid_prune function in Nerfacc, resulting in an uncertain number of points in each iteration. To address this issue and stabilize the GPU memory usage, I propose the following methods:

- Limiting the max number of sampling points that need gradient computation.
- Split the whole image rendering into several blocks to stabilize the memory usage peak.

Based on my experiment with NeRF 512x512 rendering, using 6000000 points for gradient calculation consumes about 21GB of memory, while Nerf integration requires about 16 GB. Therefore, my configuration is as follows:

```
renderer_type: "patch-renderer"
  renderer:
    mode: "interval"
    block_nums: [3,3]
    base_renderer_type: "nerf-volume-renderer"
    base_renderer:
      radius: ${system.geometry.radius}
      num_samples_per_ray: 512
      train_max_nums: 6000000
```

By utilizing the proposed configuration, the memory usage will be stabilized at ~23GB (21 + 16/(3*3)).

![memory](https://github.com/threestudio-project/threestudio/assets/24589363/4bdad3ce-dd92-45d4-9334-0624c65d16fe)

2023-06-23 18:04 UTC, DSaurus commented
Here are the results I obtained:

https://github.com/threestudio-project/threestudio/assets/24589363/eb4ab49e-d07b-460e-8b33-c0e3450edf41

2023-07-18 14:16 UTC, thuliu-yt16 commented
I see the current "interval" strategy for the nerf-renderer uses at most B // 2 samples for training. Do you think it could be better that we just randomly select `train_max_nums ` samples?

2023-07-18 14:17 UTC, thuliu-yt16 commented on threestudio/models/renderers/nerf_volume_renderer.py
> +        train_max_nums: int = -1  # 5000000
Maybe train_max_num_samples?

2023-07-18 14:18 UTC, thuliu-yt16 requested changes
Looks good! May need to further resolve conflicts when merging #217.

2023-07-18 15:03 UTC, DSaurus commented
> I see the current "interval" strategy for the nerf-renderer uses at most B // 2 samples for training. Do you think it could be better that we just randomly select `train_max_nums ` samples?

I have also implemented it by randomly selecting a continuous interval that includes `train_max_nums` samples. This method yields better results compared to the current implementation and I plan to update it later.

2023-12-02 06:02 UTC, DSaurus commented
This will be implemented in extensions.

2023-12-02 06:02 UTC, closed without merging