Fixes random_aug in background, introduces ambient_ratio_min
threestudio-project/threestudio pull request #223
Opened 2023-07-12 04:22 UTC by voletiv

1. Introduces `ambient_ratio_min` as a cfg parameter for Zero123 and ImageDreamfusion
2. Introduces `random_aug` in `solid_colour_background`
3. Fixes random_aug in background : applies a different random color background for each batch item. To make this work, unflattened `dirs` is passed to background

Earlier, the same random color was applied to every batch item. Now, a different colour is chosen for each batch item.

2023-07-12 05:37 UTC, bennyguo commented
LGTM. @DSaurus Could you please check whether the change in background affects your systems?

2023-07-12 13:16 UTC, claforte approved these changes
LGTM

2023-07-12 13:16 UTC, claforte commented on configs/zero123.yaml
> +    eval_width: 512
Zero123 eval height was 256, is now 512. (this may cause OOM for VRAM-constrained systems)

To save time, I'll add that note in your description.

2023-07-12 18:43 UTC, DSaurus requested changes
LGTM, while the color channels should be modified.

2023-07-12 22:23 UTC, voletiv commented on threestudio/models/renderers/neus_volume_renderer.py
> +            bg_color = bg_color.reshape(-1, 3)
Done!

2023-07-12 22:23 UTC, voletiv commented on threestudio/models/renderers/nerf_volume_renderer.py
> +        if bg_color.shape == (batch_size, height, width, 3):
Done!

2023-07-12 22:23 UTC, voletiv commented
Done!

2023-07-13 07:06 UTC, DSaurus approved these changes
LGTM!

2023-07-13 16:24 UTC, merged